[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "backsim"
version = "0.1.0"
description = "A backtesting simulator"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["backsim"]
